---
title: "Day 12 Challenge - The Beginning of Roman Catholicism in Korea"
author: "Jun, Youngsang"
date: "November 12, 2024"
output: 
  html_document: 
    theme: readable
    code_folding: hide
editor_options: 
  markdown: 
---

Setup
```{r setup, warning = FALSE, message = FALSE, results = "hide"}
# Load necessary libraries
library(tidycensus)
library(tidyverse)
library(sf)
library(terra)
library(rgeoboundaries)
remotes::install_github("mikejohnson51/climateR")
library(climateR)
library(biscale)
library(cowplot)
library(ggtext)
library(showtext)
library(glue)
library(ggpattern)
library(maps)
#install.packages("maps")
font_add_google("Roboto", "roboto")
showtext_auto(TRUE)
``` 
Data
``` {r data, warning = FALSE, message = FALSE, results = "hide"}
bgMap <- st_read("Data/BackgroundMap.json")
bgMap <- bgMap %>%
  st_transform(crs = "+proj=robin") 

bgMap <- bgMap %>%
  select(sovereignt, geometry) %>%
  mutate(
    sovereignt_old = case_when(
      sovereignt %in% c("South Korea", "North Korea") ~ "Joseon",
      sovereignt %in% c("China", "Taiwan", "Mongolia", "Russia") ~ "Ming-Qing",
      TRUE ~ sovereignt  
    )
  ) %>%
  group_by(sovereignt_old) %>%
  summarize(geometry = st_union(geometry)) %>%
  ungroup()


``` 

```{r}
finalMap <- ggplot() +
  theme_void(base_size = 14) +
  xlim(9400000,15800000) +
  ylim(2100000,5500000) + # Set y-axis limits for the map (latitude range)
  geom_sf(data = bgMap, fill = "#dddddd", color = "#fff") +
  geom_sf_text(data = bgMap, aes(label = sovereignt_old), size = 3, color = "#aaa", family="roboto")+

  labs(title = "The Beginning of Roman Catholicism in Korea",
       subtitle = "In the 17th century, Catholicism was introduced to Korea by envoys traveling to and from Beijing, China. Initially, it was regarded as a new field of study\nrather than a religion and was referred to as \"Western Learning (Seohak)\". It is unprecedented worldwide that Catholic faith was grown by Koreans\nthemselves before the arrival of Western missionaries.",
       caption = "Source: kkumai.tistory.com/885, contents.history.go.kr/mobile/kc/view.do?levelId=kc_n301400&code=kc_age_30,\nGitHub@yjmark, @weitzman-musa, #30DayMapChallenge #Day12")+
   theme(
    text = element_text(family = "roboto"),
    panel.background = element_rect(fill = "white", color = NA),
    panel.grid.major = element_line(color = "transparent"),         
    axis.text = element_blank(),                                     
    axis.ticks = element_blank(),                                    
    plot.title = element_text(hjust = 0, size = 18, face = "bold"),
    plot.subtitle = element_text(hjust = 0, size = 6, lineheight=0.9, face="italic", margin = margin(b = 3, t = 6)),  # Use element_markdown for ggtext
    plot.caption = element_text(size = 6, hjust = 0, lineheight = 0.9),
    plot.margin = margin(5, 5, 5, 5),
    legend.position = "none"
  ) +
    annotate("text", x = 11000000, y = 2100000, label = "Philippines", size = 3, color = "#aaa", family="roboto") +
  annotate("text", x = 11650000, y = 4145000, label = "(Korea)", size = 3, color = "#aaa", family="roboto") +
  annotate("text", x = 10200000, y = 4360000, label = "Beijing", size = 3, color = "black", family="roboto") +
      annotate("text",x = 10400000, y = 2480000, label = "Macau", size = 3, color = "black", family="roboto") +
      annotate("text",x = 11920000, y = 4030000, label = "Hanyang (Seoul)", size = 3, color = "black", family="roboto") +
     annotate("text",x = 10600000, y = 3350000, label = "Shanghai", size = 3, color = "black", family="roboto") +
        annotate("text",x = 11550000, y = 3900000, label = "Dangjin", size = 3, color = "black", family="roboto") +
  annotate("text", x = 9900000, y = 3660000, label = "Qing (China)", size = 3, color = "#aaa", family="roboto") +
  geom_richtext(aes(x = 12800000, y = 4150000), label = "
 
<b>1784</b> (1) Seunghun (Peter) Yi, the first Korean to be baptized,<br>           received baptism in Beijing, China<br>
<b>1801</b> (2) Fr. Wenmo Zhou, the first foreign (Chinese) priest of Korea,<br>was           martyred in Seoul, Korea (Sinyu Persecution)<br>
<b>1821</b> (3) Fr. Taegon (Andrew) Kim was born in Dangjin, Korea<br>
<b>1831</b> (4) The Diocese of Joseon became independent from the Diocese<br>of Beijing<br>
<b>1837</b> (5) Fr. Kim started Macau Seminary (Far Eastern Representative,<br>           Paris Foreign Missions Society) in Macau and Philippines<br>
<b>1845</b> (6) Fr. Kim, the first Korean priest, is ordained as a priest at a church in Shanghai, China<br>
<b>1846</b> (7) Fr. Kim was martyred in Seoul, Korea (Byeongo Persecution)<br>
<b>1866</b> (8) Byeongin Persecution in Seoul, Korea
           ", size = 2, color = "black", family="roboto", hjust=0, fill = NA, label.color = NA) +
    geom_point(aes(x = 10200000, y = 4220000), color = "#003749", size = 2) +
    geom_point(aes(x = 11040000, y = 4020000), color = "#003749", size = 2) +
      geom_point(aes(x = 11120000, y = 4020000), color = "#003749", size = 2) +
      geom_point(aes(x = 11200000, y = 4020000), color = "#003749", size = 2) +
      geom_point(aes(x = 11280000, y = 4020000), color = "#003749", size = 2) +
      geom_point(aes(x = 11220000, y = 3920000), color = "#003749", size = 2) +
  geom_point(aes(x = 11000000, y = 3350000), color = "#003749", size = 2) +
  geom_point(aes(x = 10400000, y = 2350000), color = "#003749", size = 2) +
  
       annotate("text",x = 10200000, y = 4220000, label = "1", color = "#fff", size = 2, family="roboto") +
     annotate("text",x = 11170000, y = 4020000, label = "2 4 7 8", color = "#fff", size = 2, family="roboto") +
       annotate("text",x = 11220000, y = 3920000, label = "3", color = "#fff", size = 2, family="roboto") +
   annotate("text",x = 11000000, y = 3350000, label = "6", color = "#fff", size = 2, family="roboto") +
   annotate("text",x = 10400000, y = 2350000, label = "5", color = "#fff", size = 2, family="roboto") 

png("12-youngsang-jun.png", width = 6, height = 4, units = 'in', res = 300)
print(finalMap)
dev.off()
```


